const PDFDocument = require("pdfkit");
const { Document, Packer, Paragraph, TextRun, HeadingLevel } = require("docx");

const buildQuoteLines = (quote) => {
  return [
    `Quote No: ${quote.quoteNo || "-"}`,
    `Country: ${quote.country || "-"}`,
    `City: ${quote.city || "-"}`,
    `Travel Date: ${quote.travelDate || "-"}`,
    `Nights: ${quote.nights ?? 0}`,
    `Rooms: ${quote.rooms ?? 0}`,
    `Adults: ${quote.adults ?? 0}`,
    `Child With Bed: ${quote.childWithBed ?? 0}`,
    `Child Without Bed: ${quote.childWithoutBed ?? 0}`,
    `Total Pax: ${quote.totalPax ?? 0}`,
    `Meal Plan: ${quote.mealPlan || "-"}`,
    `Hotel: ${quote.hotelName || "-"}`,
    `Room Type: ${quote.roomType || "-"}`,
    `Pickup Vehicle: ${quote.pickupVehicleName || "-"}`,
    `Drop Vehicle: ${quote.dropVehicleName || "-"}`,
    `Hotel Cost: $${Number(quote.hotelCost || 0).toLocaleString("en-IN")}`,
    `Transfer Cost: $${Number(quote.transferCost || 0).toLocaleString("en-IN")}`,
    `Grand Total: $${Number(quote.grandTotal || 0).toLocaleString("en-IN")}`,
  ];
};

/* =========================================================
   GENERATE PDF
========================================================= */
exports.generateQuotePdf = async (req, res) => {
  try {
    const quote = req.body;

    if (!quote || !quote.quoteNo) {
      return res.status(400).json({
        success: false,
        message: "Quote data missing"
      });
    }

    const doc = new PDFDocument({
      margin: 50,
      size: "A4"
    });

    const fileName = `${quote.quoteNo}.pdf`;

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${fileName}"`);

    doc.pipe(res);

    // Header
    doc
      .fontSize(24)
      .fillColor("#1f2a44")
      .text("TravLog Quote", { align: "center" });

    doc.moveDown(0.5);

    doc
      .fontSize(12)
      .fillColor("#6b7280")
      .text("Travel Quotation Preview", { align: "center" });

    doc.moveDown(2);

    // Quote details
    doc.fontSize(12).fillColor("#111827");

    const lines = buildQuoteLines(quote);

    lines.forEach((line) => {
      doc.text(line, {
        lineGap: 6
      });
    });

    doc.moveDown(2);

    doc
      .fontSize(10)
      .fillColor("#6b7280")
      .text("Generated by TravLog Quote Management System", {
        align: "center"
      });

    doc.end();
  } catch (error) {
    console.log("PDF GENERATE ERROR:", error);
    return res.status(500).json({
      success: false,
      message: "Failed to generate PDF"
    });
  }
};

/* =========================================================
   GENERATE WORD
========================================================= */
exports.generateQuoteWord = async (req, res) => {
  try {
    const quote = req.body;

    if (!quote || !quote.quoteNo) {
      return res.status(400).json({
        success: false,
        message: "Quote data missing"
      });
    }

    const lines = buildQuoteLines(quote);

    const doc = new Document({
      sections: [
        {
          properties: {},
          children: [
            new Paragraph({
              heading: HeadingLevel.TITLE,
              children: [
                new TextRun({
                  text: "TravLog Quote",
                  bold: true,
                  size: 36
                })
              ]
            }),

            new Paragraph({
              children: [
                new TextRun({
                  text: "Travel Quotation Preview",
                  italics: true,
                  color: "666666",
                  size: 22
                })
              ]
            }),

            new Paragraph({ text: "" }),

            ...lines.map((line) =>
              new Paragraph({
                children: [
                  new TextRun({
                    text: line,
                    size: 24
                  })
                ],
                spacing: {
                  after: 120
                }
              })
            ),

            new Paragraph({ text: "" }),

            new Paragraph({
              children: [
                new TextRun({
                  text: "Generated by TravLog Quote Management System",
                  color: "666666",
                  italics: true,
                  size: 20
                })
              ]
            })
          ]
        }
      ]
    });

    const buffer = await Packer.toBuffer(doc);
    const fileName = `${quote.quoteNo}.docx`;

    res.setHeader(
      "Content-Type",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    );
    res.setHeader("Content-Disposition", `attachment; filename="${fileName}"`);

    return res.send(buffer);
  } catch (error) {
    console.log("WORD GENERATE ERROR:", error);
    return res.status(500).json({
      success: false,
      message: "Failed to generate Word file"
    });
  }
};